### ISSUE TITLE
Characterization factor Normalization

### ISSUE THREAD

**Issue by alvarojhahn** [akoyamp/geopolrisk-py#13]
Hi there!

Thanks for the work on this package. It is a great resource.

I have a quick question. The function GeoPolRisk defines the CF as (Score*Price) but the unit is [eq. Kg-Cu/Kg].

Is the normalization to copper being done somewhere else in the code? I do not find it.

Or was this just an oversight? In that case, it is my understanding that it would be the GeoPolRisk midpoint, in [USD/kg].

Thanks for your time and assistance! 

Alvaro

https://github.com/akoyamp/geopolrisk-py/blob/fc827875e7a052f9ea83ff8a2f261501b3e69ac3/geopolrisk/assessment/core.py#L152C4-L152C23

**Comment by akoyamp** [comment]
Hi @alvarojhahn 

Thanks for raising this issue. It was indeed an oversight. I have fixed it along with some other bugs in the code.
